### ISSUE TITLE
[SUGGESTION] Use the `.github` repository for this instead

### ISSUE THREAD

**Issue by Panquesito7** [WeblateOrg/meta#292]
### Describe the problem

The `.github` repository would be a better place for these kinds of files (such as issue templates, code of conduct, etc.).
Having all these meta files in the `.github` repository will automatically use those in all other repositories. Note that repositories that already have these meta files will not be updated.

For more information: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

### Describe the solution you'd like

Rename the current repository to `.github`, so that all the GitHub community files are automatically updated in repositories that don't have these meta files. Files such as security policy should probably be removed (or only keep a very simple base), as each project has its own policy.

### Describe alternatives you've considered

Keep this repository as important meta files, and only add the base files to a new `.github` repository.

**Comment by nijel** [comment]
There already is https://github.com/WeblateOrg/.github :-). Presently, it is populated from this repository as well.

The issue templates are generated, and they differ per repository. So placing common ones there would not remove the need for this repository.

**Comment by Panquesito7** [comment]
I see. Should I close this issue or?
